### ISSUE TITLE
design-system

### ISSUE THREAD

**Issue by possible819** [drop-the-bit/gudok#2]
[Design system](https://github.com/drop-the-bit/design-system) 저장소에 디자인 시스템을 구축 합니다. 

디자인 시스템은 아래의 개발환경을 포함해야 합니다. 

- eslint
- prettier
- husky & lintstaged
- storybook
- commitlint

**Comment by possible819** [comment]
lerna + nx로 
application, component 레벨의 모듈을 모두 하나의 저장소에서 관리 할 수 있을 것 같음
[https://lerna.js.org/](https://lerna.js.org/)

**Comment by teperie** [comment]
storybook을 설치하면 컴포넌트가 빌드되지 않는 현상이 있습니다...
storybook이 사용하는 webpack 버전이 다른건지 컴포넌트의 `node_modules`아래에 `@types/webpack`가 생성되는데 여기서 문제입니다

아래는 storybook 설치 후에 button 컴포넌트를 빌드하려다 생긴 에러입니다

![image](https://user-images.githubusercontent.com/77098015/186430538-59acd8e1-a365-48db-b3f1-d04f29239f67.png)
```
[webpack-cli] webpack.config.ts:2:26 - error TS2497: This module can only be referenced with ECMAScript imports/exports by turning on the 'esModuleInterop' flag and referencing its default export.

2 import * as webpack from 'webpack'
```


들여다보면 이렇게 되어있습니다
`@types/webpack/index.d.ts`
<img width="344" alt="image" src="https://user-images.githubusercontent.com/77098015/186431293-4c76ef5c-6ac3-48ad-a2da-4961aa600794.png">

그냥 날려버려도 빌드는 되지만 애초에 방지하려면 어디를 조정해야할지 감이 안 잡히네요

**Comment by possible819** [comment]
@teperie 
커밋 해주시면 저도 한번 확인해 볼게요
storybook이 내부에서 사용하는 webpack 있고 그걸 변경할 수 있는 설정이 있는걸로 알고 있는데 정확한 원인은 확인해 봐야 알겠네요

**Comment by teperie** [comment]
https://github.com/drop-the-bit/gudok-client/tree/storybook
이 브랜치에 작업돼있습니다

내용은 dev 브랜치의 husky 등등 툴 작업 커밋 직후 storybook만 올린 것이고
`npx sb init -t react -b webpack5` <- 이 스크립트로 설치했습니다
(-t로 프로젝트 타입 지정 안 하면 create-react-app으로 인식합니다. 뭘 보고 이런 건진 모르겠어요. -b는 빌더 옵션입니다)
-f 플래그를 붙이면 덮어씌우고 다시 설치할 수 있습니다

lerna로 storybook 자체를 컴포넌트처럼 분리도 해봤는데 같은 현상이 나타납니다... webpack 버전이 다르니까 yarn이 알아서 해주는거라고 추정만 하는데 그렇다쳐도 button 안에서 왜 에러나는 코드를 만들어주는 건지 모르겠네요

**Comment by possible819** [comment]
<img width="651" alt="Screen Shot 2022-08-25 at 2 03 19 PM" src="https://user-images.githubusercontent.com/12540307/186579156-2de5c36c-a3bc-48e0-9eef-42ca676990b1.png">
이런식으로 수정하면 정상적으로 동작하는 것 같네요
아무래도 commonjs랑 typescript랑 컴파일 하면서 임포트하는 방식에 차이가 있어서 그런것 같은데 정확한 원인은 한번 파악해 보면 좋을 것 같아요 👍

**Comment by possible819** [comment]
@teperie 따로 수정하지는 않을게요 수정 부탁드립니다.
